#!/bin/sh
set -eu
squid_uid="$(id -u squid)"
owner_rule="--uid-owner (squid|${squid_uid}) -j ACCEPT"
iptables -S OUTPUT | grep -q '^-P OUTPUT DROP$'
iptables -S OUTPUT | grep -q -- '-A OUTPUT -o lo -j ACCEPT'
iptables -S OUTPUT | grep -Eq -- "$owner_rule"
iptables -S OUTPUT | grep -q -- '-A OUTPUT -j REJECT'
if [ -r /proc/net/if_inet6 ] && grep -vq ' lo$' /proc/net/if_inet6; then
  ip6tables -S OUTPUT | grep -q '^-P OUTPUT DROP$'
  ip6tables -S OUTPUT | grep -q -- '-A OUTPUT -o lo -j ACCEPT'
  ip6tables -S OUTPUT | grep -Eq -- "$owner_rule"
  ip6tables -S OUTPUT | grep -q -- '-A OUTPUT -j REJECT'
fi
[ "$(cat /proc/1/comm)" = "squid" ]
